### PR TITLE
Added Name to Developer Name list

### PR DESCRIPTION
**Pull request by S-chahine**
Added Name to Developer Name list

### CODE REVIEW

**Review by AnnaSolovykh — APPROVED** [review]

**Review by ElenaCherpakova — APPROVED** [review]

**Comment by Nassimancer** [comment]
That pull request was for the onboarding and it blocked.

**Comment by AnnaSolovykh** [comment]
> That pull request was for the onboarding and it blocked.

What do you by saying "blocked"?

**Comment by Nassimancer** [comment]
I mean the merging is blocked

**Comment by AnnaSolovykh** [comment]
It is blocked because we need three reviews to unblock merging. Three people should check every PR before we can merge. Triple check:)

**Review by Nassimancer — APPROVED** [review]

**Comment by Nassimancer** [comment]
Okay thank you Anna for the clarifications :)

**Review by nadezdatsygankova — APPROVED** [review]

**Review by VrushaliHaldankar01 — APPROVED** [review]

**Comment by Alaleh-kash** [comment]
Added Name to Developer Name list

**Comment by AnnaSolovykh** [comment]
@S-chahine Samah, I have run the code and have seen some linting issues which are absent in main.
Screenshot 2024-06-18 at 22 28 10
Screenshot 2024-06-18 at 22 29 07

**Pull request closed without merging**
