### PR TITLE
Fix/106/buttons styling

### PR DESCRIPTION
**Pull request by KatePolyakov**
Styled signin and signout buttons as figma design and according task https://github.com/users/JULIERAJ/projects/2?pane=issue&itemId=67755652

### CODE REVIEW

**Review by AnnaSolovykh — CHANGES_REQUESTED** [review]
I can see that the buttons in Sign Up and Sign In look amazing and totally reflect the design in figma! Great job, Kate, well done! You promised to do on Friday - you did it, I appreciate this approach!

However, in the scope of the issue there were also some other buttons. Could fix them too please?  There are totally broken now and we need to show them nicely on Tuesday to Juliette...
Just in case, I am not talking about Google and Facebook which we will discuss during the meeting, I mean these ones: 
Screenshot 2024-06-21 at 17 08 17
App (this screenshot - and actually if you tap the button you can see the buttons are broken throughout the whole workflow): 
Screenshot 2024-06-21 at 17 08 29

**Review by nadezdatsygankova — APPROVED** [review]
Great job!

**Comment by KatePolyakov** [comment]
> However, in the scope of the issue there were also some other buttons. Could fix them too please? There are totally broken now and we need to show them nicely on Tuesday to Juliette... Just in case, I am not talking about Google and Facebook which we will discuss during the meeting,

Buttons fixed, please review.

Screenshot 2024-06-24 11 00 13
Screenshot 2024-06-24 11 00 15

Screenshot 2024-06-24 10 41 39
Screenshot 2024-06-24 10 41 43
Screenshot 2024-06-24 11 00 09

**Review by ElenaCherpakova — APPROVED** [review]

**Review by AnnaSolovykh — APPROVED** [review]

**Comment by AnnaSolovykh** [comment]
@KatePolyakov thanks, looks great!

**Pull request merged**
